#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################
# Name : Anlominus ~ TryHackMe
# Description : TryHackMe ~ Tools .
# Created Date : 2022 July 6
# Aouther: Anlominus ~> RhytMix ~> TryHackMe
# Skils: Best Copywriter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: To All World Creators free Scripts & Tools
# Location: Made With LOVE IN ISRAEL !
# Source: https://github.com/Anlominus/TryHackMe/TryHackMe
###############################################
clear
chmod +x $0
###############################################

# Define Colors Variables
AnLoMinusColors(){
##############################################################################
# COLORS AND BACKGROUNDS
##############################################################################
Color_Off='\033[0m' # Text Reset

# Regular Colors
Black='\033[0;30m'  # Black
Red='\033[0;31m'    # Red
Green='\033[0;32m'  # Green
Yellow='\033[0;33m' # Yellow
Blue='\033[0;34m'   # Blue
Purple='\033[0;35m' # Purple
Cyan='\033[0;36m'   # Cyan
White='\033[0;97m'  # White

# Additional colors
LGrey='\033[0;37m'   # Ligth Gray
DGrey='\033[0;90m'   # Dark Gray
LRed='\033[0;91m'    # Ligth Red
LGreen='\033[0;92m'  # Ligth Green
LYellow='\033[0;93m' # Ligth Yellow
LBlue='\033[0;94m'   # Ligth Blue
LPurple='\033[0;95m' # Light Purple
LCyan='\033[0;96m'   # Ligth Cyan


# Bold
BBlack='\033[1;30m'  # Black
BRed='\033[1;31m'    # Red
BGreen='\033[1;32m'  # Green
BYellow='\033[1;33m' # Yellow
BBlue='\033[1;34m'   # Blue
BPurple='\033[1;35m' # Purple
BCyan='\033[1;36m'   # Cyan
BWhite='\033[1;37m'  # White

# Underline
UBlack='\033[4;30m'  # Black
URed='\033[4;31m'    # Red
UGreen='\033[4;32m'  # Green
UYellow='\033[4;33m' # Yellow
UBlue='\033[4;34m'   # Blue
UPurple='\033[4;35m' # Purple
UCyan='\033[4;36m'   # Cyan
UWhite='\033[4;37m'  # White

}
AnLoMinusColors

Logo(){
  echo "
${BRed} ███████████                     ${BYellow} █████   █████                    █████     ${BBlue} ██████   ██████
${BRed}░█░░░███░░░█                     ${BYellow}░░███   ░░███                    ░░███      ${BBlue}░░██████ ██████
${BRed}░   ░███  ░  ████████  █████ ████${BYellow} ░███    ░███   ██████    ██████  ░███ █████${BBlue} ░███░█████░███   ██████
${BRed}    ░███    ░░███░░███░░███ ░███ ${BYellow} ░███████████  ░░░░░███  ███░░███ ░███░░███ ${BBlue} ░███░░███ ░███  ███░░███
${BRed}    ░███     ░███ ░░░  ░███ ░███ ${BYellow} ░███░░░░░███   ███████ ░███ ░░░  ░██████░  ${BBlue} ░███ ░░░  ░███ ░███████
${BRed}    ░███     ░███      ░███ ░███ ${BYellow} ░███    ░███  ███░░███ ░███  ███ ░███░░███ ${BBlue} ░███      ░███ ░███░░░
${BRed}    █████    █████     ░░███████ ${BYellow} █████   █████░░████████░░██████  ████ █████${BBlue} █████     █████░░██████
${BRed}   ░░░░░    ░░░░░       ░░░░░███ ${BYellow}░░░░░   ░░░░░  ░░░░░░░░  ░░░░░░  ░░░░ ░░░░░ ${BBlue}░░░░░     ░░░░░  ░░░░░░
${BRed}                        ███ ░███ ${ToolVersion}
${BRed}                       ░░██████
${BRed}                        ░░░░░░                                                                        "
}
###############################################

# Arsenal Cheatsheets
Arsenal(){
  clear
  # Getting Arsenal Cheatsheets
  if [ -d == ./Arsenal ]; then
    #statements
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Installed  \n"
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}cd Into Arsenal\n"
    cd Arsenal
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}List Arsenal Directories \n"
    ls -lahs
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Runnin  \n"
    ./run
  fi
  if [[ -d $HOME/opt/anaconda3/bin/arsenal ]]; then
    #statements
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Installed  \n"
    break
  else
    #statements
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Creating Folder Arsenal \n"
    mkdir Arsenal
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${LYellow}Cloning Into [./Arsenal] \n"
    git clone https://github.com/Orange-Cyberdefense/Arsenal ./Arsenal
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}cd Into Arsenal\n"
    cd Arsenal
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}List Arsenal Directories \n"
    ls -lahs
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Installing Arsenal Requirements \n"
    python3 -m pip install -r requirements.txt
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Run Installation  \n"
    ./run
    if [[ $? == 1 ]]; then
      #statements
      echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Installation ${BRed} ERROR  \n"
    fi
    echo "\n\n"
    echo "\n\t\t ${BRed}[${BCyan}Readed Command${BRed}]${BBlue} - ${BYellow} $ReaDone  \n"
    read -p "$Press_ENTER" ArsenalCommand

  fi
  cd ..

}

###############################################

# Checking If User is Root
CheckingIfRoot(){
  ROOT_UID=0
  if [ "$UID" -eq "$ROOT_UID" ]; then
    echo "Yes, you are root."
  else
    echo "No, you are not root"
  fi
}

###############################################

# Checking For System Package Manager
Check_System() {
  # checking for system package manager
  if [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
  elif [ `command -v brew` ]; then
    pac="brew"
    system="mac"
    sudo=""
  elif [ `command -v apt` ]; then
    pac="apt"
    system="linux"
  elif [ `command -v apt-get` ]; then
    pac="apt-get"
    system="linux"
  elif [ `command -v apk` ]; then
    pac="apk"
    system="linux"
  elif [ `command -v yum` ]; then
    pac="yum"
    system="fedora"
  fi

  # checking for system root access
  if [ `command -v sudo` ]; then
    sudo="sudo"
  else
    sudo=""
  fi

  # checking for system home dir
  if [ -d $HOME ]; then
    home=$HOME
  else
    home="~/"
  fi

  # checking for system bin dir
  if [ -d /data/data/com.termux/files/usr/bin ]; then
    bin="/data/data/com.termux/files/usr/bin"
  elif [ -d /usr/local/bin ]; then
    bin="/usr/local/bin"
  elif [ -d /bin ]; then
    bin="/bin"
  elif [ -d /sbin ]; then
    bin="/sbin"
  fi

}
Check_System


# Checking Running Direction
CheckPWD(){
  # Define Current Direction Variable
  CheckingDirectory="$(pwd)"
  # Assign $CheckingDirectory to $MainDirectoriy
  MainDirectoriy="$CheckingDirectory"
}
CheckPWD

###############################################

# Checking If we set Target
Checking_IP_Target(){
  if [ -z $targetIP ]; then
    #statements
    clear
    HacKingProLogo1
    echo "
      ${BBlue}[${BRed}ERROR${BBlue}] ${BYellow} ❌ ${BRed}Error; ${LRed}You need Enter IP Before Scanning;

      ${BRed}[${DGrey}P${BRed}]${BBlue} -${DGrey} ⚡️ Planning and Scoping 🎯
      ${BRed}=======================================================================================
      ${BBlue}[🗓 ]  ${FullTime} $(date)
      ${BBlue}[🗓 ]  ${CurrentDate}
      ${BBlue}[🗓 ]  ${StartingTime}
      ${DGrey}=======================================================================================
      ${BBlue}┌──[ 🎯 ]──[${BRed}$(FunTargetIP)${BBlue}]──╼  ${LRed}IP${BBlue}: ${BGreen}${targetIP}
      ${BBlue}|──[ 🎯 ]──[${BRed}$(FunTargetDns)${BBlue}]──╼  ${LRed}Dns${BBlue}: ${BGreen}${targetDns}
      ${BBlue}|──[ 🎯 ]──[${BRed}$(FunTargetName)${BBlue}]──╼  ${LRed}Name${BBlue}: ${BGreen}${targetNAME}
      ${BBlue}|──[ 🎯 ]──[${BRed}$(FunTargetEmail)${BBlue}]──╼  ${LRed}Email${BBlue}: ${BGreen}${targetEmail}
      ${BBlue}└──[ 🎯 ]──[${BRed}$(FunTargetPhone)${BBlue}]──╼  ${LRed}Phone${BBlue}: ${BGreen}${targetPhone}
      ${BRed}=======================================================================================
      ${BRed}[${DGrey}I${BRed}]${BBlue} - ${DGrey}Install HacKingPro On the System"

      echo "\n          ${BRed}[${DGrey}P${BRed}]${BBlue} - ${BGreen} [p|P] ${DGrey} On Keyboard and Come Back!!! `date`"
      sleep 1
      echo "\n          ${BRed}[${DGrey}P${BRed}]${BBlue} - ${BGreen} [p|P] ${DGrey} On Keyboard and Come Back!!! `date`"
      sleep 1
      echo "\n          ${BRed}[${DGrey}P${BRed}]${BBlue} - ${BGreen} [p|P] ${DGrey} On Keyboard and Come Back!!! `date`"
      sleep 1
      echo "\n          ${BRed}[${DGrey}P${BRed}]${BBlue} - ${BGreen} [p|P] ${DGrey} On Keyboard and Come Back!!! `date`"
      sleep 1
      echo "\n          ${BRed}[${DGrey}P${BRed}]${BBlue} - ${BGreen} [p|P] ${DGrey} On Keyboard and Come Back!!! `date`"
      sleep 1
      read -p "$Press_ENTER" readthat
      cd "$XHacKingPro"
  fi

}

# Checking if Case Folder Exist
CheckingifCaseFolderExist(){
  ReadTargetNameFromtheUser
  #statements
  if [ -d Case ]; then
    echo "\n  ${BBlue}|────${BRed}[ ✅ ${BRed}]${BBlue}──╼ ${BGreen}Case ${BYellow}Folder Exists, Continue to it\n"
    cd Case
    if [ -d $targetNAME ]; then
      #statements
      echo "  ${BBlue}|────${BRed}[ ✅ ${BRed}]${BBlue}──╼ ${BGreen}$targetNAME ${BYellow}Folder Exists, Continue to it\n"
      cd $targetNAME
    else
      mkdir $targetNAME
      cd $targetNAME
    fi
    if [ -d Planning ]; then
      #statements
      echo "  ${BBlue}|────${BRed}[ ✅ ${BRed}]${BBlue}──╼ ${BGreen}$targetNAME/Planning ${BYellow}Folder Exists, Continue to it\n"
      cd Planning
    else
      mkdir Planning
      cd Planning
    fi
  else
    echo "\n  ${BBlue}|────${BRed}[ ❌ ${BRed}]${BBlue}──╼ ${BGreen}Case ${BYellow}Folder Not Exists, Create it\n"
    echo "  ${BBlue}|────${BRed}[ ✅ ${BRed}]${BBlue}──╼ ${BYellow}Creating ${BGreen}Case ${BYellow}Folder and Continue to it\n"
    mkdir Case
    cd Case
    echo "  ${BBlue}|────${BRed}[ ✅ ${BRed}]${BBlue}──╼ ${BYellow}Creating ${BGreen}$targetNAME ${BYellow}and Continue to it\n"
    mkdir $targetNAME
    cd $targetNAME
    echo "  ${BBlue}|────${BRed}[ ✅ ${BRed}]${BBlue}──╼ ${BYellow}Creating ${BGreen}Case Planning ${BYellow}and Continue to it\n"
    mkdir Planning
    cd Planning
  fi

  # This Variable for Naming File Report
  Planning_File="${targetNAME}-HacKingPro-Planning-Log.md"
  if [ -e ${Planning_File} ]; then
    t5="$(echo "  ${BBlue}|────${BRed}[ ❌ ${BRed}]${BBlue}──╼${BGreen} $Planning_File ${BGreen} ${BYellow}Exist! ${LRed}Remove it? ${BCyan}[yY/nN]: ")"
    read -p "$t5 " filexist
    case $filexist in
      y|Y)
      cd "$XHacKingProCaseTargetName/Planning"
      echo "    ${BBlue}|────${BRed}[ 🔶 ${BRed}]${BBlue}──╼${BGreen}  Removing {${Planning_File}} file .."
      read -p "$Press_ENTER"
      rm ${Planning_File}
      echo "    ${BBlue}|────${BRed}[ ❌ ${BRed}]${BBlue}──╼${BGreen} ✅ Removed {${Planning_File}} file .."
      cd "$XHacKingProCaseTargetName"
      ;;
      n|N)
      echo "    ${BBlue}|────${BRed}[ 🔶 ${BRed}]${BBlue}──╼${BGreen} Leaving {${Planning_File}} file .."
      ;;
    esac
  fi

}

###############################################

# Read Target Name From the User
ReadTargetNameFromtheUser(){
  # Read Target Name From the User
  # This Variable is for Case Name.
  t0="$(echo "\n  ${BBlue}┌──[ 🎯 ]──[${BRed} Name ${BBlue}]──╼  ")"
  read -p "$t0" targetNAME
  if [ -z $targetNAME ]; then
    #statements
    targetNAME="AnLoMinus"
    # echo "\n\t  ${BRed}[${LGrey}TN${BRed}]${BBlue} - ${LGrey}Target Name ${BBlue} $targetNAME\n"
  fi

  # Checking if Case Folder Exist

}

# Define Variables For Case Directory
TryHackMeCase="${MainDirectoriy}/Case"

# Read Target Name From the User
ReadTargetNameFromtheUser(){
  # Read Target Name From the User
  # This Variable is for Case Name.
  t0="$(echo "\n  ${BBlue}┌──[ 🎯 ]──[${BRed} Name ${BBlue}]──╼  ")"
  read -p "$t0" targetNAME
  if [ -z $targetNAME ]; then
    #statements
    targetNAME="AnLoMinus"
    # echo "\n\t  ${BRed}[${LGrey}TN${BRed}]${BBlue} - ${LGrey}Target Name ${BBlue} $targetNAME\n"
  fi
}

# Read Target IP From the User
ReadTargetIPFromtheUser(){
# Read Target URL / Domain / Dns / Server From the User
# This Variable is for AttacKing ~> IP Addresses .
t1="$(echo "\n  ${BBlue}|──[ 🎯 ]──[${BRed} IP ${BBlue}]──╼  ")"
read -p "$t1" targetIP
if [ -z $targetIP ]; then
  #statements
  targetIP="127.0.0.1"
  # targetIP=" "
  echo "> - ### Target IP: ${targetIP}" >> ${targetNAME}-HacKingPro-Planning-Log.md
fi
}

# Read Target URL From the User
ReadTargetURLFromtheUser(){
# Read Target URL / Domain / Dns / Server From the User
# This Variable is for OSINT and AttacKing ~> URL / Domain / Dns / Server/ Websites .
t2="$(echo "\n  ${BBlue}|──[ 🎯 ]──[${BRed} URL ${BBlue}]──╼  ")"
read -p "$t2" targetDns
if [ -z $targetDns ]; then
  #statements
  targetDns="xXx.AnLoMinus.xXx"
  echo "> - ### Target Dns: ${targetDns}" >> ${targetNAME}-HacKingPro-Planning-Log.md
fi
}

# Read Target Email From the User
ReadTargetEmailFromtheUser(){
# Read Target Email From the User
# This Variable is for OSINT and AttacKing ~> Emails .
t3="$(echo "\n  ${BBlue}|──[ 🎯 ]──[${BRed} Email ${BBlue}]──╼  ")"
read -p "$t3" targetEmail
if [ -z $targetEmail ]; then
  #statements
  targetEmail="Change.Me@Do.Now"
  # echo "\n${BRed}[${LGrey}TE${BRed}]${BBlue} - ${LGrey}Target Email ${BBlue} $targetEmail\n"
  echo "> - ### Target Email: ${targetEmail}" >> ${targetNAME}-HacKingPro-Planning-Log.md
fi
}

# Read Target Phone From the User
ReadTargetPhoneFromtheUser(){
# Read Target Phone From the User
# This Variable is for OSINT and AttacKing ~> Phones Numbers .
t4="$(echo "\n  ${BBlue}└──[ 🎯 ]──[${BRed} Phone (With Country Code) ${BBlue}]──╼  ")"
read -p "$t4" targetPhone
if [ -z $targetPhone ]; then
  #statements
  targetPhone="9720506933037"
  # echo "\n${BRed}[${LGrey}TP${BRed}]${BBlue} - ${LGrey}Target Phone ${BBlue} $targetPhone\n"
fi
echo "> - ### Target Phone: ${targetPhone}" >> ${targetNAME}-HacKingPro-Planning-Log.md
}

# Planning and Scoping
TryHackMePlanning(){
  clear
  Logo

  cd "$MainDirectoriy"

  # Menu
  HacKingProTargetStatus=$(echo "\n
    ${BRed}[${DGrey}P${BRed}]${BBlue} -${DGrey} ⚡️ Planning and Scoping 🎯
    ${BRed}=======================================================================================
    ${BBlue}[🗓 ]  ${FullTime} $(date)
    ${BBlue}[🗓 ]  ${CurrentDate}
    ${BBlue}[🗓 ]  ${StartingTime}
    ${DGrey}=======================================================================================
    ${BBlue}┌──[ 🎯 ]──[${BRed}$(FunTargetIP)${BBlue}]──╼  ${LRed}IP${BBlue}: ${BGreen}${targetIP}
    ${BBlue}|──[ 🎯 ]──[${BRed}$(FunTargetDns)${BBlue}]──╼  ${LRed}Dns${BBlue}: ${BGreen}${targetDns}
    ${BBlue}|──[ 🎯 ]──[${BRed}$(FunTargetName)${BBlue}]──╼  ${LRed}Name${BBlue}: ${BGreen}${targetNAME}
    ${BBlue}|──[ 🎯 ]──[${BRed}$(FunTargetEmail)${BBlue}]──╼  ${LRed}Email${BBlue}: ${BGreen}${targetEmail}
    ${BBlue}└──[ 🎯 ]──[${BRed}$(FunTargetPhone)${BBlue}]──╼  ${LRed}Phone${BBlue}: ${BGreen}${targetPhone}
    ${BRed}=======================================================================================
    ${DGrey}|──[ ~$(pwd) ]
  ")
  echo "$HacKingProTargetStatus"

  CheckingifCaseFolderExist

  # Recommended Open With `Atom` Editor For Normal View.
  echo "# Recommended Open With [Atom]() or [Obsidian]() Editor For Normal View." >> ${targetNAME}-HacKingPro-Planning-Log.md
  echo "### $targetNAME Case Date: `date`" >> ${targetNAME}-HacKingPro-Planning-Log.md
  echo "> - ### Target Name: ${targetNAME}" >> ${targetNAME}-HacKingPro-Planning-Log.md

  ReadTargetIPFromtheUser
  ReadTargetURLFromtheUser
  ReadTargetEmailFromtheUser
  ReadTargetPhoneFromtheUser

  #
  echo "\n${BRed}[${BYellow}🔸${BRed}]${BBlue} - ${BYellow}Listing Case \n"
  echo "${BYellow} Log Directory ${BRed}[${BGreen} $(pwd) ${BRed}]\n${BGreen}"
  echo "${BYellow} Log File ${BRed}[${BGreen} $(ls) ${BRed}]\n${BGreen}"
  echo "$TryHackMeCase"
  read -p "$Press_ENTER"
  cd "$TryHackMeCase"
  cd "$targetNAME"

}


# Planning Status
FunTargetDns(){
  #statements
  if [ -z ${targetDns} ]; then
    TargetDnsStatusOFF=" ❌ "
    echo "${TargetDnsStatusOFF}"
  else
    targetDnsStatusON=" ✅ "
    echo "${targetDnsStatusON}"
  fi
}
FunTargetIP(){
  #statements
  if [ -z ${targetIP} ]; then
    TargetIpStatusOFF=" ❌ "
    echo "${TargetIpStatusOFF}"
  else
    TargetIpStatusON=" ✅ "
    echo "${TargetIpStatusON}"
  fi
}
FunTargetName(){
  #statements
  if [ -z ${targetNAME} ]; then
    TargetNameStatusOFF=" ❌ "
    echo "${TargetNameStatusOFF}"
  else
    TargetNameStatusON=" ✅ "
    echo "${TargetNameStatusON}"
  fi
}
FunTargetEmail(){
  #statements
  if [ -z ${targetEmail} ]; then
    TargetEmailStatusOFF=" ❌ "
    echo "${TargetEmailStatusOFF}"
  else
    TargetEmailStatusON=" ✅ "
    echo "${TargetEmailStatusON}"
  fi
}
FunTargetPhone(){
      #statements
      if [ -z ${targetPhone} ]; then
        TargetPhoneStatusOFF=" ❌ "
        echo "${TargetPhoneStatusOFF}"
      else
        TargetPhoneStatusON=" ✅ "
        echo "${TargetPhoneStatusON}"
      fi
    }

###############################################

# TryHackMe Main Menu
TryHackMe_Menu(){
  # Parsing Date and Time
  ToolName="TryHackMe"
  ToolAouther="AnLoMinus"
  ToolVersion="v0.0.0.4"
  LastUPDATE= "2022 July 6"
  year=$(date +%Y)
  month=$(date +%m)
  day=$(date +%d)
  hour=$(date +%H)
  minute=$(date +%M)
  second=$(date +%S)
  CurrentDate=$(echo "Current Date${BBlue}: ${DGrey}$day-$month-$year")
  StartingTime=$(echo "Starting Time${BBlue}: ${DGrey}$hour:$minute:$second")
  FullTime=$(echo "Full Time${BBlue}:${DGrey} ")

  # HacKingPro
  TryHackMe=$(echo "${BRed}Try${BYellow}Hack${BBlue}Me")
  HacKingProDavid=$(echo "\n\t  ${BRed}[${BCyan}✡${BRed}] ${TryHackMe} ${BRed}[${BCyan}✡${BRed}]\n\t\t ${BGreen}")
  HacKingProExit=$(echo "\n ${BRed}[${BCyan}✡${BRed}] ${BCyan}Exit ${TryHackMe} ${BRed}[${BCyan}✡${BRed}]\n\t\t ${BGreen}")
  Press_ENTER=$(echo "\n\n${BYellow}                🔶    Press ENTER    🔶     ${BGreen}\n\n")
  Press_Enter_To_START=$(echo "\n\n${BYellow}                🔶    Press Enter To START    🔶     ${BGreen}\n\n")

  while true; do
    #statements
    clear
    Logo
    # HacKingProLogo1
    HacKingProTargetStatus=$(echo "\n
    ${BRed}[${DGrey}P${BRed}]${BBlue} -${DGrey} ⚡️ Planning and Scoping 🎯
    ${BRed}=======================================================================================
    ${BBlue}[🗓 ]  ${FullTime} $(date)
    ${BBlue}[🗓 ]  ${CurrentDate}
    ${BBlue}[🗓 ]  ${StartingTime}
    ${DGrey}=======================================================================================
    ${BBlue}┌──[ 🎯 ]──[${BRed}$(FunTargetIP)${BBlue}]──╼  ${LRed}IP${BBlue}: ${BGreen}${targetIP}
    ${BBlue}|──[ 🎯 ]──[${BRed}$(FunTargetDns)${BBlue}]──╼  ${LRed}Dns${BBlue}: ${BGreen}${targetDns}
    ${BBlue}|──[ 🎯 ]──[${BRed}$(FunTargetName)${BBlue}]──╼  ${LRed}Name${BBlue}: ${BGreen}${targetNAME}
    ${BBlue}|──[ 🎯 ]──[${BRed}$(FunTargetEmail)${BBlue}]──╼  ${LRed}Email${BBlue}: ${BGreen}${targetEmail}
    ${BBlue}└──[ 🎯 ]──[${BRed}$(FunTargetPhone)${BBlue}]──╼  ${LRed}Phone${BBlue}: ${BGreen}${targetPhone}
    ${BRed}=======================================================================================
    ${BRed}[${DGrey}P${BRed}]${BBlue} -${DGrey} ⚡️ Planning and Scoping 🎯


    ${BRed}[${BYellow}KoTH${BRed}]${BBlue} - ${BYellow}🤴🏼 King of The Hill ⛰

    ")

    HacKingProMenuMain=$(echo "${BRed}
    ${BBlue}[${BYellow}#${BBlue}] ${BYellow} 📜 TryHackMe Menu ⌖"

          echo "$HacKingProTargetStatus""
    ${BRed}[${LGrey}x${BRed}]${BWhite} -${DGrey} Exit / Quit / Close

    ${BBlue}┌──${BBlue}[${BRed} Arsenal ${BBlue}]${BBlue} - ${DGrey}[${BBlue} Cheat Sheets ${DGrey}] ${BRed}~ ${DGrey}[${BRed} Command ${DGrey}]${BCyan}: $BGreen $ArsenalCommand
    ${BBlue}|
    ${DGrey}|──[ ~$(pwd) ]
    ${DGrey}|
    ${BYellow}└──[ $ToolAouther 👽 ${TryHackMe} ${BYellow}]──╼${BGreen}  ")
          read -p "$HacKingProMenuMain" cmd
          case $cmd in
            arsenal|Arsenal|cs|CS|cheats|Cheatsheets|CheatSheets|Commands|commands|zz )
            Arsenal
            ;;
            ls )
            ls_lahs="$(echo "\n\t ${BRed}[🙏🏼${BRed}] ${BWhite}List Files ~ Executing: ls -lahs ${HacKingPro} ${BRed}[🙏🏼${BRed}]\n\t\t ${HacKingPro}")"
            echo "$ls_lahs"
            sleep 2
            ls -lahs
            sleep 2
            read -p "$ls_lahs" cmd
            ;;
            x|X|exit|quit|Exit )
            clear
            echo "$HacKingProExit"
            break
            ;;
            p|P|planning|Planning )
            TryHackMePlanning
            ;;

          esac
done
}
TryHackMe_Menu
