#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                        YaraPro.                             #
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-YaraPro ]                 #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 25-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 25-08-2022 ]                              #
###############################################################
clear
YaraColors(){
##############################################################################
# COLORS AND BACKGROUNDS
##############################################################################
Color_Off='\033[0m' # Text Reset
BYellow='\033[1;33m' # Yellow
}
YaraColors

echo "\n\t\t 🔶 ${BYellow} Downloading YARA v4.2.1.tar.gz"
sleep 1
wget https://github.com/VirusTotal/yara/archive/v4.2.1.tar.gz
echo "\n\t\t 🔶 ${BYellow} Extracting YARA v4.2.1.tar.gz"
sleep 1
tar -zxvf v4.2.1.tar.gz
rm v4.2.1.tar.gz
echo "\n\t\t 🔶 ${BYellow} Compile & Install"
sleep 1
cd yara-4.2.1
chmod +x configure
./configure
chmod +x bootstrap.sh
./bootstrap.sh
make
sudo make install
echo "\n\t\t ✅ ${BGreen}YARA v4.2.1 Installed"
sleep 1
read -p "    Press ENTER    " press_ENTER
