#!/bin/sh
#!/bin/bash
#!/usr/bin/bash
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/bash
###############################################
# Last UPDATE : 2022 Jun 20
# Create Date : 2022 Jun 20
# Location: Made With LOVE IN ISRAEL !
# Skils: Best Copywriter IN the COSMOS!
# Description: Yara Istaller by @Anlominus
# CREDIT: To All World Creators free Scripts & Tools
# Aouther: Anlominus ~> TryHackMe ~> YARA ~> install
# Name : Anlominus ~> TryHackMe ~> Room ~> YARA ~> install
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# Source: https://github.com/Anlominus/TryHackMe/tree/main/Room/YARA
###############################################
clear

YaraColors(){
##############################################################################
# COLORS AND BACKGROUNDS
##############################################################################
Color_Off='\033[0m' # Text Reset
BYellow='\033[1;33m' # Yellow
}
YaraColors

echo "\n\t\t 🔶 ${BYellow} Downloading YARA v4.2.1.tar.gz"
sleep 1
wget https://github.com/VirusTotal/yara/archive/v4.2.1.tar.gz
echo "\n\t\t 🔶 ${BYellow} Extracting YARA v4.2.1.tar.gz"
sleep 1
tar -zxvf v4.2.1.tar.gz
rm v4.2.1.tar.gz
echo "\n\t\t 🔶 ${BYellow} Compile & Install"
sleep 1
cd yara-4.2.1
chmod +x configure
./configure
chmod +x bootstrap.sh
./bootstrap.sh
make
sudo make install
echo "\n\t\t ✅ ${BGreen}YARA v4.2.1 Installed"
sleep 1
read -p "    Press ENTER    " press_ENTER
